name: GitHub Actions Build KKT
on:
  push:
    branches:
      - master
jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - run: npm install --unsafe-perm
      - run: npm run hoist
      - run: npm run b:kkt
      - run: npm run b:plugin
      - run: npm run b:example:basic
      - run: npm run b:example:less
      - run: npm run b:example:markdown
