name: Build KKT & Example
on:
  push:
    branches:
      - master

env:
  SKIP_PREFLIGHT_CHECK: true
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Look Changelog
        uses: jaywcjlove/changelog-generator@v1.3.9
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filter-author: (jaywcjlove|小弟调调™|dependabot\[bot\]|Renovate Bot)
          filter: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'

      - run: npm install --unsafe-perm
      - run: npm run hoist
      - run: npm run kkt:build
      - run: npm run lib:build
      - run: npm run b:example:bundle
      - run: npm run b:example:bundle.pro
      - run: npm run b:example:bundle.min
      - run: npm run b:example:bundle-react-component-tsx
      - run: npm run b:example:less
      - run: npm run b:example:markdown
      - run: npm run b:example:react-component-tsx
      - run: npm run b:example:rematch
      - run: npm run b:example:rematch-hash-router
      - run: npm run b:example:rematch-tsx
      - run: npm run b:example:rematch-uiw
      - run: npm run b:example:stylus
      - run: npm run b:example:typescript
      - run: npm run b:example:uiw

      - run: npm run b:example:scss
      - run: npm run b:example:basic

      - name: Is a tag created auto?
        id: create_tag
        uses: jaywcjlove/create-tag-action@v1.1.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          package-path: ./core/package.json

      - name: Generate Changelog
        id: changelog
        uses: jaywcjlove/changelog-generator@v1.3.9
        if: steps.create_tag.outputs.successful
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          head-ref: ${{steps.create_tag.outputs.version}}
          filter-author: (jaywcjlove|小弟调调™|dependabot\[bot\]|Renovate Bot)
          filter: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        if: steps.create_tag.outputs.successful
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.create_tag.outputs.version }}
          release_name: ${{ steps.create_tag.outputs.version }}
          body: |
            ${{ steps.changelog.outputs.compareurl }}
            ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false

      - name: npm publish
        if: steps.create_tag.outputs.successful
        run: node ./node_modules/.bin/lerna publish from-package --yes --no-verify-access
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}