name: Build KKT & Example
on:
  push:
    branches:
      - master

env:
  SKIP_PREFLIGHT_CHECK: true
jobs:
  windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@master

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Look Changelog
        uses: jaywcjlove/changelog-generator@v1.3.9
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filter-author: (jaywcjlove|小弟调调™|dependabot\[bot\]|Renovate Bot)
          filter: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'
      - run: npm install --unsafe-perm
      - run: npm run hoist
      - run: npm run kkt:build
      - run: npm run lib:build

  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Look Changelog
        uses: jaywcjlove/changelog-generator@v1.3.9
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filter-author: (jaywcjlove|小弟调调™|dependabot\[bot\]|Renovate Bot)
          filter: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'

      - run: npm install --unsafe-perm
      - run: npm run hoist
      - run: npm run kkt:build
      - run: npm run lib:build
      - run: npm run b:example:bundle
      - run: npm run b:example:bundle.pro
      - run: npm run b:example:bundle.min
      - run: npm run b:example:bundle-react-component-tsx
      - run: npm run b:example:less
      - run: npm run b:example:markdown
      - run: npm run b:example:react-component-tsx
      - run: npm run b:example:rematch
      - run: npm run b:example:rematch-hash-router
      - run: npm run b:example:rematch-tsx
      - run: npm run b:example:rematch-uiw
      - run: npm run b:example:stylus
      - run: npm run b:example:typescript
      - run: npm run b:example:uiw

      - run: npm run b:example:scss
      - run: npm run b:example:basic

      - name: Is a tag created auto?
        id: create_tag
        uses: jaywcjlove/create-tag-action@v1.1.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          package-path: ./core/package.json

      - name: Generate Changelog
        id: changelog
        uses: jaywcjlove/changelog-generator@v1.3.9
        if: steps.create_tag.outputs.successful
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          head-ref: ${{steps.create_tag.outputs.version}}
          filter-author: (jaywcjlove|小弟调调™|dependabot\[bot\]|Renovate Bot)
          filter: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        if: steps.create_tag.outputs.successful
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.create_tag.outputs.version }}
          release_name: ${{ steps.create_tag.outputs.version }}
          body: |
            ${{ steps.changelog.outputs.compareurl }}
            ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false

      - run: npm run ci:publish
        if: steps.create_tag.outputs.successful
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - run: mkdir -p zip

      - name: Compress basic Example.
        run: zip -r -y basic.zip . -x "node_modules/*" -x "build/*" -x "coverage/*" -x ".eslintcache" -x "sandbox.config.json"
        working-directory: example/basic
      - run: cp -rp example/basic/basic.zip ./zip

      - name: Compress bundle Example.
        run: zip -r -y bundle.zip . -x "node_modules/*" -x "build/*" -x "dist/*" -x "coverage/*" -x ".eslintcache" -x "sandbox.config.json"
        working-directory: example/bundle
      - run: cp -rp example/bundle/bundle.zip ./zip

      - name: Compress bundle-react-component-tsx Example.
        run: zip -r -y bundle-react-component-tsx.zip . -x "node_modules/*" -x "build/*" -x "dist/*" -x "coverage/*" -x ".eslintcache" -x "sandbox.config.json"
        working-directory: example/bundle-react-component-tsx
      - run: cp -rp example/bundle-react-component-tsx/bundle-react-component-tsx.zip ./zip

      - name: Compress chrome-plugin Example.
        run: zip -r -y chrome-plugin.zip . -x "node_modules/*" -x "build/*" -x "dist/*" -x "coverage/*" -x ".eslintcache" -x "sandbox.config.json"
        working-directory: example/chrome-plugin
      - run: cp -rp example/chrome-plugin/chrome-plugin.zip ./zip

      - name: Compress electron Example.
        run: zip -r -y electron.zip . -x "node_modules/*" -x "build/*" -x "dist/*" -x "coverage/*" -x ".eslintcache" -x "sandbox.config.json"
        working-directory: example/electron
      - run: cp -rp example/electron/electron.zip ./zip

      - name: Compress less Example.
        run: zip -r -y less.zip . -x "node_modules/*" -x "build/*" -x "dist/*" -x "coverage/*" -x ".eslintcache" -x "sandbox.config.json"
        working-directory: example/less
      - run: cp -rp example/less/less.zip ./zip

      - name: Compress less Example.
        run: zip -r -y less.zip . -x "node_modules/*" -x "build/*" -x "dist/*" -x "coverage/*" -x ".eslintcache" -x "sandbox.config.json"
        working-directory: example/less
      - run: cp -rp example/less/less.zip ./zip

      - name: Compress markdown Example.
        run: zip -r -y markdown.zip . -x "node_modules/*" -x "build/*" -x "dist/*" -x "coverage/*" -x ".eslintcache" -x "sandbox.config.json"
        working-directory: example/markdown
      - run: cp -rp example/markdown/markdown.zip ./zip

      - name: Compress react-component-tsx Example.
        run: zip -r -y react-component-tsx.zip . -x "node_modules/*" -x "build/*" -x "dist/*" -x "coverage/*" -x ".eslintcache" -x "sandbox.config.json"
        working-directory: example/react-component-tsx
      - run: cp -rp example/react-component-tsx/react-component-tsx.zip ./zip

      - name: Compress rematch Example.
        run: zip -r -y rematch.zip . -x "node_modules/*" -x "build/*" -x "dist/*" -x "coverage/*" -x ".eslintcache" -x "sandbox.config.json"
        working-directory: example/rematch
      - run: cp -rp example/rematch/rematch.zip ./zip

      - name: Compress rematch-hash-router Example.
        run: zip -r -y rematch-hash-router.zip . -x "node_modules/*" -x "build/*" -x "dist/*" -x "coverage/*" -x ".eslintcache" -x "sandbox.config.json"
        working-directory: example/rematch-hash-router
      - run: cp -rp example/rematch-hash-router/rematch-hash-router.zip ./zip

      - name: Compress rematch-tsx Example.
        run: zip -r -y rematch-tsx.zip . -x "node_modules/*" -x "build/*" -x "dist/*" -x "coverage/*" -x ".eslintcache" -x "sandbox.config.json"
        working-directory: example/rematch-tsx
      - run: cp -rp example/rematch-tsx/rematch-tsx.zip ./zip

      - name: Compress rematch-uiw Example.
        run: zip -r -y rematch-uiw.zip . -x "node_modules/*" -x "build/*" -x "dist/*" -x "coverage/*" -x ".eslintcache" -x "sandbox.config.json"
        working-directory: example/rematch-uiw
      - run: cp -rp example/rematch-uiw/rematch-uiw.zip ./zip

      - name: Compress scss Example.
        run: zip -r -y scss.zip . -x "node_modules/*" -x "build/*" -x "dist/*" -x "coverage/*" -x ".eslintcache" -x "sandbox.config.json"
        working-directory: example/scss
      - run: cp -rp example/scss/scss.zip ./zip

      - name: Compress stylus Example.
        run: zip -r -y stylus.zip . -x "node_modules/*" -x "build/*" -x "dist/*" -x "coverage/*" -x ".eslintcache" -x "sandbox.config.json"
        working-directory: example/stylus
      - run: cp -rp example/stylus/stylus.zip ./zip

      - name: Compress typescript Example.
        run: zip -r -y typescript.zip . -x "node_modules/*" -x "build/*" -x "dist/*" -x "coverage/*" -x ".eslintcache" -x "sandbox.config.json"
        working-directory: example/typescript
      - run: cp -rp example/typescript/typescript.zip ./zip

      - name: Compress uiw Example.
        run: zip -r -y uiw.zip . -x "node_modules/*" -x "build/*" -x "dist/*" -x "coverage/*" -x ".eslintcache" -x "sandbox.config.json"
        working-directory: example/uiw
      - run: cp -rp example/uiw/uiw.zip ./zip

      - name: Upload *.zip Files
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN_KKT }}
          external_repository: kktjs/zip
          publish_branch: gh-pages
          publish_dir: ./zip
