name: GitHub Actions Build KKT
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - run: npm b:example:basic
      - run: npm b:example:bundle
      - run: npm b:example:bundle.pro
      - run: npm b:example:bundle.min
      - run: npm b:example:less
      - run: npm b:example:markdown
      - run: npm b:example:react-component-tsx
      - run: npm b:example:rematch
      - run: npm b:example:rematch-hash-router
      - run: npm b:example:rematch-tsx
      - run: npm b:example:rematch-uiw
      - run: npm b:example:scss
      - run: npm b:example:stylus
      - run: npm b:example:typescript
      - run: npm b:example:uiw
